/*
 * generated by Xtext 2.23.0
 */
package io.activise.philyra.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import io.activise.philyra.PhilyraRuntimeModule;
import io.activise.philyra.PhilyraStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PhilyraIdeSetup extends PhilyraStandaloneSetup {

  @Override
  public Injector createInjector() {
    return Guice.createInjector(Modules2.mixin(new PhilyraRuntimeModule(), new PhilyraIdeModule()));
  }

}
